# These are supported funding model platforms

github: [telegramS7] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: [https://t.me/s7airlinesrblx, https://t.me/Siyanie_ak_rbx, https://t.me/GeorgijSoldatov, https://t.me/qsi_1] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
